# Generated by Django 2.0 on 2017-12-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('state', models.BooleanField()),
                ('provider', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('begined', models.DateTimeField(verbose_name='date de debut')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categorie')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewnumber', models.IntegerField()),
                ('clicknumber', models.IntegerField()),
                ('viewtime', models.TimeField()),
                ('viewdate', models.DateField()),
                ('viewierid', models.CharField(max_length=20)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('content', models.TextField(verbose_name='Description')),
                ('created', models.DateField()),
                ('price', models.IntegerField(verbose_name='Le prix')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('video', models.CharField(default=None, max_length=250, verbose_name='Lien video')),
                ('links', models.ImageField(max_length=250, upload_to='uploads/%Y/%m/%d/', verbose_name='Image 1')),
                ('links1', models.ImageField(default=None, max_length=250, upload_to='uploads/%Y/%m/%d/', verbose_name='Image 2 ')),
                ('links2', models.ImageField(default=None, max_length=250, upload_to='uploads/%Y/%m/%d/', verbose_name='Image 3 ')),
                ('links3', models.ImageField(default=None, max_length=250, upload_to='uploads/%Y/%m/%d/', verbose_name='Image 4')),
                ('links4', models.ImageField(default=None, max_length=250, upload_to='uploads/%Y/%m/%d/', verbose_name='Image  5 ')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categorie')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='referer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
