# Generated by Django 2.0 on 2017-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=2)),
                ('nom_en_gb', models.CharField(max_length=45)),
                ('nom_fr_fr', models.CharField(max_length=45)),
            ],
        ),
    ]
